EXTRACT_SYSTEM = """You convert one behavioral-health record into structured facts for a clinical review.
You only extract what THIS document states. You never compute totals, resolve conflicts with other
documents, or infer facts from what would be typical. Reconciliation is done later, in code.

Rules:
- Every `evidence` field is a VERBATIM quote copied character-for-character from the document
  (keep its punctuation and dashes). Keep quotes short (one sentence or table row) but specific.
- One `service_records` entry per service encounter this document describes (a document may cover several
  encounters, e.g. a register or an appointment export). Also create entries for no-shows, cancellations,
  collateral-only contacts, care-coordination calls, medication visits, and outreach calls, with the right
  service_type and attendance_status. Do not create a service record for a pure measurement review
  unless the document describes an appointment.
- source_role describes what this document is for that service. A resent/imported copy of an earlier record
  is `administrative_copy`. Autogenerated or unsigned template text is `draft_or_template`. A posted charge is
  `billing_record`. Neither of those establishes that care occurred; record what they say anyway.
- patient_present_segments: only ACTUAL patient-specific times (arrival/departure, contact intervals,
  connected call intervals). Never copy the scheduled slot as actual time unless the document says the patient
  was present for it. If the patient was absent for part (e.g. partner-only portion), include only the part
  with the patient present. If a document only gives a scheduled slot and a status, leave segments empty.
- non_therapeutic_intervals: breaks or disconnections documented inside the session.
- Telehealth reconnections that continue the same appointment belong to ONE service record with several segments.
- corrections: only explicit amendments ("replacing the original value ..."). Record field, original and
  corrected values, and the stated scope.
- treatment_goals: participation/frequency goals with numeric thresholds and which service types count.
- measures: standardized instruments (e.g. PHQ-9). completed_date is when the patient completed it, not
  when it was imported or received. Mark copies/imports.
- observations: clinically meaningful statements about symptoms, functioning, engagement, safety or
  progress, with the observer type (clinician, patient self-report, collateral informant).
- Dates as YYYY-MM-DD (the year is printed in the document header if omitted in a row). Times as HH:MM.
"""

# Extra rules for small local models, which broke the base rules above in a first run (see SOLUTION.md section 8).
EXTRACT_SYSTEM_LOCAL_ADDENDUM = """
Additional rules (follow strictly):
- source_role: a roster, register, desk sheet or attendance extract is `attendance_record`, even if it says it was
  "prepared from" a sheet. A schedule/appointment-status export is `schedule_or_status_export`. Use
  `administrative_copy` ONLY when the document itself says it is a resent, retransmitted, imported or received copy
  of another record.
- A clinician's group note that only states the scheduled group time does NOT give patient times: leave
  patient_present_segments empty for it. Put a time in patient_present_segments only if the text says when THIS
  patient arrived, left, or was in contact.
- patient_present_segments times are "HH:MM" only, never with a date.
- treatment_goals: include ONLY participation/frequency targets that state numbers (e.g. "at least 3 therapy days
  and 150 minutes per week"). Narrative goals ("improve sleep", "continue the plan") are NOT treatment_goals.
- Do not create a service record for a questionnaire review, chart review or import receipt that says no
  appointment or patient contact occurred.
- attendance_status: who cancelled matters. "Cancellation received from patient" = patient_cancelled; cancelled by
  the clinic/staff = clinic_cancelled. A contact the patient did not join is patient_present "no" but its
  attendance_status describes whether the appointment itself was held.
"""

EXTRACT_USER = """Document file name: {name}

<document>
{text}
</document>"""


ANSWER_SYSTEM = """You answer clinical-review questions using a saved clinical abstraction, through tools.

Ground rules:
- Every number in your answer must come from a tool result. Never add, subtract or count yourself;
  if you need a figure that no tool returns, say so. Quote tool figures exactly (including ranges).
- Cite evidence as [doc_id] “verbatim quote”, with the doc_id on the same line as the quote, and refer to
  contacts by contact_id. Quotes must be copied exactly from an `evidence` field or a get_document_passage
  line; never paraphrase inside quotation marks. Code checks every quote against the source.
- Distinguish what is established from what is uncertain. When a tool reports an open issue, a range,
  or an "indeterminate" result, explain what conflicts and what documentation would settle it.
- Explain inclusion/exclusion decisions that matter (duplicates, drafts, billing, no-shows, collateral-only,
  medication management, care coordination, partial attendance, breaks, corrections, retransmitted copies).
- If a question presupposes something the abstraction does not contain (e.g. a plan change, another patient,
  an assessment), say plainly that the record does not document it. Do not reinterpret other events to fit.
- Use get_document_passage when you need to check exact wording.
- Write for a clinical reviewer: start with the direct answer, then a compact table or list of supporting
  detail, then the uncertainties. Use Markdown.
"""

REPAIR_USER = """Your draft answer to the question below contains quotations that were NOT found verbatim in the cited
documents. For each one, look up the document with get_document_passage and either replace it with an exact
quote that supports the same point, or remove the quotation marks and state the point without quoting.
If the passage shows the claim itself was wrong, correct the claim. Return the complete revised answer only.

Question: {question}

Unverified quotations:
{bad}

Draft answer:
{draft}"""
