"""JSON schema for per-document extraction (OpenAI strict structured outputs).

Every fact carries `evidence`: a verbatim quote that verify.py locates in the source.
Times are HH:MM 24h local; dates are YYYY-MM-DD. Minutes are *not* derived by the
model from times - code does that - but stated minute totals are captured as written.
"""

SERVICE_TYPES = [
    "individual_psychotherapy", "group_psychotherapy", "family_psychotherapy",
    "collateral_contact", "medication_management", "care_coordination",
    "measure_or_questionnaire_review", "scheduling_or_outreach", "authorization_or_administrative", "other",
]
SOURCE_ROLES = [
    "clinical_note",            # clinician's narrative record of a service
    "attendance_record",        # roster / register / desk sheet with patient arrival-departure or disposition
    "schedule_or_status_export",# appointment desk export, scheduled times and statuses
    "correction",               # explicit amendment of an earlier record
    "cancellation_or_no_show_log",
    "telehealth_platform_log",
    "draft_or_template",        # unsigned / autogenerated text
    "billing_record",
    "administrative_copy",      # resent / imported / retransmitted copy of another record
    "other",
]
ATTENDANCE = ["attended_full", "attended_partial", "attended_unspecified", "no_show", "patient_cancelled",
              "clinic_cancelled", "not_held", "scheduled_only", "not_applicable", "unknown"]
PRESENT = ["yes", "no", "partial", "unknown"]
CORRECTION_FIELDS = ["arrival", "departure", "attendance_status", "service_date", "duration", "other"]
OBS_DOMAINS = ["mood", "anxiety", "sleep", "functioning_activity", "avoidance", "work_return", "engagement",
               "safety", "family_support", "overall_progress", "other"]
OBSERVER = ["clinician", "patient_self_report", "collateral_informant", "administrative"]


def _s(desc=None, nullable=False, enum=None):
    t = {"type": ["string", "null"] if nullable else "string"}
    if enum:
        t["enum"] = enum + ([None] if nullable else [])
    if desc:
        t["description"] = desc
    return t


def _obj(props: dict) -> dict:
    return {"type": "object", "additionalProperties": False, "properties": props, "required": list(props)}


INTERVAL = _obj({
    "start": _s("HH:MM"),
    "end": _s("HH:MM"),
    "evidence": _s("verbatim quote stating this interval"),
})

SERVICE_RECORD = _obj({
    "encounter_id": _s("encounter identifier printed in the document, e.g. HG-E110", nullable=True),
    "appointment_id": _s(nullable=True),
    "service_date": _s("YYYY-MM-DD"),
    "service_type": _s(enum=SERVICE_TYPES),
    "source_role": _s("what kind of record this document is FOR THIS SERVICE", enum=SOURCE_ROLES),
    "attendance_status": _s(enum=ATTENDANCE),
    "patient_present": _s("was the patient themself present for any therapeutic contact", enum=PRESENT),
    "modality": _s(enum=["in_person", "video", "phone", "unknown"]),
    "scheduled_start": _s("booked/scheduled start HH:MM", nullable=True),
    "scheduled_end": _s(nullable=True),
    "patient_present_segments": {
        "type": "array", "items": INTERVAL,
        "description": "ACTUAL intervals when THIS PATIENT was present in therapeutic contact, as stated in this "
                       "document (actual arrival-departure, contact intervals, connected call intervals). Exclude "
                       "portions where only other people (e.g. partner) were present. Do NOT copy the scheduled "
                       "slot unless the document says the patient was actually present for it. Do not subtract "
                       "breaks here. Empty if this document gives no patient-specific actual times."},
    "non_therapeutic_intervals": {
        "type": "array", "items": INTERVAL,
        "description": "documented breaks, disconnections or other intervals inside the session with no therapy"},
    "stated_patient_minutes": {"type": ["integer", "null"],
                               "description": "patient-present therapy minutes exactly as stated in the text, if stated"},
    "clinicians": {"type": "array", "items": {"type": "string"}},
    "other_participants": _s("e.g. partner, outside professional", nullable=True),
    "signed_final": {"type": "boolean", "description": "this record is signed/attested and final (not draft)"},
    "signer_and_time": _s(nullable=True),
    "reason_for_service": _s("why this service occurred / was added, if stated", nullable=True),
    "notes": _s("anything a reviewer needs: late arrival, early departure, retransmission, template text", nullable=True),
    "evidence": _s("verbatim quote that best establishes this record's status"),
})

CORRECTION = _obj({
    "encounter_id": _s(nullable=True),
    "service_date": _s("date of the service being corrected, YYYY-MM-DD"),
    "field": _s(enum=CORRECTION_FIELDS),
    "original_value": _s(nullable=True),
    "corrected_value": _s(),
    "scope": _s("what the correction says it applies to and does not change"),
    "evidence": _s(),
})

GOAL = _obj({
    "min_therapy_days_per_week": {"type": ["integer", "null"]},
    "min_patient_present_minutes_per_week": {"type": ["integer", "null"]},
    "week_definition": _s("e.g. Monday-Sunday", nullable=True),
    "counted_service_types": {"type": "array", "items": _s(enum=SERVICE_TYPES)},
    "excluded_service_types": {"type": "array", "items": _s(enum=SERVICE_TYPES)},
    "therapy_day_definition": _s(nullable=True),
    "effective_from": _s("YYYY-MM-DD", nullable=True),
    "effective_to": _s("YYYY-MM-DD", nullable=True),
    "plan_signed_date": _s(nullable=True),
    "evidence": _s(),
})

MEASURE = _obj({
    "instrument": _s("e.g. PHQ-9"),
    "total_score": {"type": ["number", "null"]},
    "item_detail": _s("e.g. item 9 score", nullable=True),
    "completed_date": _s("date the PATIENT completed it (not import/receipt date), YYYY-MM-DD"),
    "source_form_id": _s(nullable=True),
    "is_copy_or_import": {"type": "boolean", "description": "this document reproduces a result recorded elsewhere"},
    "evidence": _s(),
})

OBSERVATION = _obj({
    "date": _s("date the observation refers to, YYYY-MM-DD"),
    "domain": _s(enum=OBS_DOMAINS),
    "observer_type": _s(enum=OBSERVER),
    "observer": _s(nullable=True),
    "summary": _s("one short sentence"),
    "evidence": _s(),
})

EXTRACTION = _obj({
    "document": _obj({
        "printed_document_id": _s("ID printed in the document, e.g. BH-D003", nullable=True),
        "title": _s(),
        "patient_name": _s(nullable=True),
        "patient_mrn": _s(nullable=True),
        "patient_dob": _s("YYYY-MM-DD", nullable=True),
        "document_date": _s("signature/creation date YYYY-MM-DD", nullable=True),
        "is_retransmission_or_copy": {"type": "boolean"},
        "copy_of": _s("which original record this copies, if any", nullable=True),
        "summary": _s("one sentence"),
    }),
    "service_records": {"type": "array", "items": SERVICE_RECORD},
    "corrections": {"type": "array", "items": CORRECTION},
    "treatment_goals": {"type": "array", "items": GOAL},
    "measures": {"type": "array", "items": MEASURE},
    "observations": {"type": "array", "items": OBSERVATION},
    "administrative_facts": {"type": "array", "items": _obj({"fact": _s(), "evidence": _s()})},
})
